import os
import re
import tempfile
import requests

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

DARK_BLUE = RGBColor(24,39,75)
WHITE = RGBColor(255,255,255)
BLACK = RGBColor(40,40,40)
LIGHT = RGBColor(248,249,251)

def clean(text):
    text = re.sub(r"^#+\s*", "", text)
    text = text.replace("**","").replace("__","").replace("`","")
    return text.strip()

def download(url):
    if not url:
        return None
    try:
        r=requests.get(url,timeout=20)
        r.raise_for_status()
        f=tempfile.NamedTemporaryFile(delete=False,suffix=".jpg")
        f.write(r.content)
        f.close()
        return f.name
    except Exception:
        return None

def add_image(slide,url,left,top,width):
    path=download(url)
    if path:
        try:
            slide.shapes.add_picture(path,left,top,width=width)
        finally:
            os.remove(path)

def generate_ppt(title, report, hero, sections, filename):
    os.makedirs(os.path.dirname(filename),exist_ok=True)

    prs=Presentation()
    prs.slide_width=Inches(13.33)
    prs.slide_height=Inches(7.5)

    # Cover
    slide=prs.slides.add_slide(prs.slide_layouts[6])
    slide.background.fill.solid()
    slide.background.fill.fore_color.rgb=DARK_BLUE

    tb=slide.shapes.add_textbox(Inches(.6),Inches(.3),Inches(12),Inches(.7))
    p=tb.text_frame.paragraphs[0]
    p.text=clean(title)
    p.font.size=Pt(30)
    p.font.bold=True
    p.font.color.rgb=WHITE
    p.alignment=PP_ALIGN.CENTER

    add_image(slide, hero.get("image_url") if hero else None,
              Inches(2), Inches(1.1), Inches(9))

    st=slide.shapes.add_textbox(Inches(.8),Inches(6.7),Inches(11.5),Inches(.4))
    sp=st.text_frame.paragraphs[0]
    sp.text="Generated by AI Research Studio"
    sp.font.size=Pt(18)
    sp.font.color.rgb=WHITE
    sp.alignment=PP_ALIGN.CENTER

    # Section slides
    for section in sections:
        s=prs.slides.add_slide(prs.slide_layouts[6])
        s.background.fill.solid()
        s.background.fill.fore_color.rgb=LIGHT

        ht=s.shapes.add_textbox(Inches(.5),Inches(.3),Inches(12),Inches(.5))
        hp=ht.text_frame.paragraphs[0]
        hp.text=clean(section["title"])
        hp.font.size=Pt(24)
        hp.font.bold=True
        hp.font.color.rgb=DARK_BLUE

        add_image(s,
                  section.get("image",{}).get("image_url") if section.get("image") else None,
                  Inches(7.9), Inches(1), Inches(4.8))

        body=s.shapes.add_textbox(Inches(.5),Inches(1),Inches(7),Inches(5.8))
        tf=body.text_frame
        tf.clear()

        lines=section["content"].splitlines()
        first=True
        for line in lines:
            line=clean(line)
            if not line:
                continue
            if line.startswith("- ") or line.startswith("* "):
                line=line[2:].strip()
            p=tf.paragraphs[0] if first else tf.add_paragraph()
            first=False
            p.text="• "+line
            p.font.size=Pt(18)
            p.font.color.rgb=BLACK
            p.space_after=Pt(6)

    prs.save(filename)
    return filename
