import os
import re

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_AUTO_SHAPE_TYPE
from pptx.dml.color import RGBColor

# ---------------- COLORS ---------------- #

DARK_BLUE = RGBColor(24, 39, 75)
PURPLE = RGBColor(124, 58, 237)
WHITE = RGBColor(255, 255, 255)
BLACK = RGBColor(40, 40, 40)
LIGHT_BG = RGBColor(248, 249, 251)

# ---------------------------------------- #


def add_title_bar(slide, title):

    bar = slide.shapes.add_shape(
        MSO_AUTO_SHAPE_TYPE.RECTANGLE,
        0,
        0,
        Inches(13.33),
        Inches(0.65),
    )

    bar.fill.solid()
    bar.fill.fore_color.rgb = DARK_BLUE
    bar.line.color.rgb = DARK_BLUE

    tb = slide.shapes.add_textbox(
        Inches(0.45),
        Inches(0.08),
        Inches(11),
        Inches(0.45),
    )

    p = tb.text_frame.paragraphs[0]
    p.text = title
    p.font.size = Pt(26)
    p.font.bold = True
    p.font.color.rgb = WHITE


def add_footer(slide, page):

    tb = slide.shapes.add_textbox(
        Inches(0.4),
        Inches(7.0),
        Inches(12),
        Inches(0.3),
    )

    p = tb.text_frame.paragraphs[0]
    p.text = f"AI Research Studio{' '*35}Slide {page}"
    p.font.size = Pt(10)
    p.font.color.rgb = PURPLE


# -----------------------------------------------------


def split_sentences(text):

    text = re.sub(r"\s+", " ", text.strip())

    return [
        s.strip(" .")
        for s in re.split(r"(?<=[.!?])\s+", text)
        if len(s.strip()) > 12
    ]


# -----------------------------------------------------


def parse_sections(report):

    headings = [
        "Introduction",
        "Main Findings",
        "Applications",
        "Challenges",
        "Future Scope",
        "Conclusion",
        "Recommendations",
    ]

    sections = []

    current_title = "Research Summary"
    current_text = []

    for line in report.splitlines():

        line = line.strip()

        if not line:
            continue

        clean = line.replace("*", "").replace(":", "").strip()

        matched = False

        for h in headings:

            if clean.lower() == h.lower():

                if current_text:
                    sections.append(
                        (
                            current_title,
                            " ".join(current_text),
                        )
                    )

                current_title = h
                current_text = []
                matched = True
                break

        if not matched:
            current_text.append(line)

    if current_text:
        sections.append((current_title, " ".join(current_text)))

    return sections


# -----------------------------------------------------


def add_content_slide(prs, title, bullets, page):

    slide = prs.slides.add_slide(prs.slide_layouts[6])

    bg = slide.background.fill
    bg.solid()
    bg.fore_color.rgb = LIGHT_BG

    add_title_bar(slide, title)

    textbox = slide.shapes.add_textbox(
        Inches(0.8),
        Inches(0.95),
        Inches(11.8),
        Inches(5.7),
    )

    tf = textbox.text_frame
    tf.clear()

    first = True

    for bullet in bullets:

        if first:
            p = tf.paragraphs[0]
            first = False
        else:
            p = tf.add_paragraph()

        p.text = bullet
        p.level = 0

        p.font.size = Pt(20)
        p.font.color.rgb = BLACK

        p.space_after = Pt(10)
        p.line_spacing = 1.2

    add_footer(slide, page)


# -----------------------------------------------------


def generate_ppt(title, report, filename):

    os.makedirs(os.path.dirname(filename), exist_ok=True)

    prs = Presentation()

    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)

    # ---------------- COVER ---------------- #

    slide = prs.slides.add_slide(prs.slide_layouts[6])

    bg = slide.background.fill
    bg.solid()
    bg.fore_color.rgb = DARK_BLUE

    tb = slide.shapes.add_textbox(
        Inches(0.8),
        Inches(1.5),
        Inches(11),
        Inches(1),
    )

    p = tb.text_frame.paragraphs[0]
    p.text = title
    p.font.size = Pt(34)
    p.font.bold = True
    p.font.color.rgb = WHITE
    p.alignment = PP_ALIGN.CENTER

    sub = slide.shapes.add_textbox(
        Inches(1),
        Inches(2.5),
        Inches(10.5),
        Inches(0.5),
    )

    p = sub.text_frame.paragraphs[0]
    p.text = "Generated by AI Research Studio"
    p.font.size = Pt(20)
    p.font.color.rgb = WHITE
    p.alignment = PP_ALIGN.CENTER

    page = 2

    sections = parse_sections(report)

    for heading, text in sections:

        sentences = split_sentences(text)

        bullets = []

        for s in sentences:

            s = re.sub(r"^\*\*(.*?)\*\*", "", s).strip()

            if s:
                bullets.append(s)

        if not bullets:
            continue

        for i in range(0, len(bullets), 5):

            add_content_slide(
                prs,
                heading,
                bullets[i:i + 5],
                page,
            )

            page += 1

    # ---------------- THANK YOU ---------------- #

    slide = prs.slides.add_slide(prs.slide_layouts[6])

    bg = slide.background.fill
    bg.solid()
    bg.fore_color.rgb = DARK_BLUE

    tb = slide.shapes.add_textbox(
        Inches(2),
        Inches(2.3),
        Inches(9),
        Inches(1),
    )

    p = tb.text_frame.paragraphs[0]
    p.text = "Thank You"
    p.font.size = Pt(36)
    p.font.bold = True
    p.font.color.rgb = WHITE
    p.alignment = PP_ALIGN.CENTER

    prs.save(filename)

    return filename